[package]
name = "peggy"
version = "0.0.1"
edition = "2021"
description = "WIP"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
once_cell = "1.10"
